//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatrixTechAssessment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MatrixTechAssessment.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {data:[{HospitalID:369,ImplantDate:&apos;Nov  2 2013 12:00AM&apos;,Gender:&apos;Male&apos;},{HospitalID:369,ImplantDate:&apos;Feb  7 2014 12:00AM&apos;,Gender:&apos;Female&apos;},{HospitalID:369,ImplantDate:&apos;Feb  3 2013 12:00AM&apos;,Gender:&apos;Female&apos;},{HospitalID:369,ImplantDate:&apos;Dec 23 2013 12:00AM&apos;,Gender:&apos;Male&apos;},{HospitalID:369,ImplantDate:&apos;Jan 13 2013 12:00AM&apos;,Gender:&apos;Male&apos;},{HospitalID:369,ImplantDate:&apos;Dec 12 2010 12:00AM&apos;,Gender:&apos;Male&apos;},{HospitalID:369,ImplantDate:&apos;Sep 16 2013 12:00AM&apos;,Gender:&apos;Male&apos;},{HospitalID:369,ImplantDate:&apos;Feb 17 2008 12:00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonData {
            get {
                return ResourceManager.GetString("JsonData", resourceCulture);
            }
        }
    }
}
